blank_issues_enabled: false
contact_links:
  - name: Tra cứu trong sách trước
    url: https://github.com/Gaorb80/HowToLiveBetter#mục-lục
    about: Xem mục lục để tìm chủ đề. Nội dung bạn cần có thể đã được đề cập trong sách.
